### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by wxharry** [team-tumbleweed/gdrive-upload-action#18]
Hi, I am using `gdrive-upload-action` to upload an .pdf output to google drive. But got an file not found error
``` shell
:error::creating file: &{AppProperties:map[] Capabilities:<nil> ContentHints:<nil> ContentRestrictions:[] CopyRequiresWriterPermission:false CreatedTime: Description: DriveId: ExplicitlyTrashed:false ExportLinks:map[] FileExtension: FolderColorRgb: FullFileExtension: HasAugmentedPermissions:false HasThumbnail:false HeadRevisionId: IconLink: Id: ImageMediaMetadata:<nil> IsAppAuthorized:false Kind: LastModifyingUser:<nil> Md5Checksum: MimeType: ModifiedByMe:false ModifiedByMeTime: ModifiedTime: Name:resume_Harry_Wu.pdf OriginalFilename: OwnedByMe:false Owners:[] Parents:[***] PermissionIds:[] Permissions:[] Properties:map[] QuotaBytesUsed:0 Shared:false SharedWithMeTime: SharingUser:<nil> ShortcutDetails:<nil> Size:0 Spaces:[] Starred:false TeamDriveId: ThumbnailLink: ThumbnailVersion:0 Trashed:false TrashedTime: TrashingUser:<nil> Version:0 VideoMediaMetadata:<nil> ViewedByMe:false ViewedByMeTime: ViewersCanCopyContent:false WebContentLink: WebViewLink: WritersCanShare:false ServerResponse:{HTTPStatusCode:0 Header:map[]} ForceSendFields:[] NullFields:[]} failed with error: googleapi: Error 404: File not found: ***., notFound
```
I am sure that that .pdf file is successfully generated and I also tried to upload the source .tex file but it also failed with the same error.

Here is my yml file:
```
name: Build_and_release
on: push
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex

      - name: upload to google drive
        uses: team-tumbleweed/gdrive-upload-action@main
        with:
          filename: resume.pdf
          name: resume_Harry_Wu.pdf
          folderId: ${{ secrets.folderId }}
          credentials: ${{ secrets.credentials }}
          encoded: false
```

Really apperciate your work and help!
Thanks!
